/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.apache.beam.runners.direct.DirectRunner;
import org.apache.beam.sdk.Pipeline;
import org.apache.beam.sdk.options.Default;
import org.apache.beam.sdk.options.Description;
import org.apache.beam.sdk.options.PipelineOptionsFactory;
import org.apache.beam.sdk.options.PipelineOptions;
import org.apache.beam.sdk.transforms.Create;
import org.apache.beam.sdk.transforms.MapElements;
import org.apache.beam.sdk.transforms.SimpleFunction;
import org.example.dags.Dag;
import org.example.dags.HelloWorldDag;

public class App {

    public interface DagOptions extends PipelineOptions {
        @Description("Dag options")
        @Default.String("HELLOWORLD")
        String getDagType();
        void setDagType(String dagType);
    }
    public static void main(String[] args) {
        DagOptions options = PipelineOptionsFactory
                .fromArgs()
                .withValidation()
                .as(DagOptions.class);
        Pipeline p = Pipeline.create(options);

        Dag dag = Dispatcher.dispatch(DagType.valueOf(options.getDagType()));
        dag.process(p);
        p.run().waitUntilFinish();
    }
}
