/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */

version = "v0.0.1"
val repositoryUrl: String = System.getenv("DOCKER_REPOS_URL") ?: "myrepos"
val dockerTag: String = System.getenv("GIT_REV") ?: "${project.version}"

plugins {
    id("com.palantir.docker") version "0.36.0"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    testCompileOnly("junit:junit:4.13.1")
    testRuntimeOnly("org.junit.vintage:junit-vintage-engine")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    testRuntimeOnly("com.fasterxml.jackson.core:jackson-databind:2.16.0")

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(platform("org.apache.beam:beam-sdks-java-google-cloud-platform-bom:2.57.0"))
    implementation("org.apache.beam:beam-sdks-java-core")
    implementation("org.apache.beam:beam-runners-direct-java")
    implementation("org.apache.beam:beam-sdks-java-io-rrio")
    implementation("org.apache.beam:beam-sdks-java-extensions-avro")
    implementation("com.google.api-client:google-api-client:2.6.0")
    compileOnly("com.google.auto.value:auto-value-annotations:1.11.0")
    annotationProcessor("com.google.auto.value:auto-value:1.11.0")
    implementation("org.hamcrest:hamcrest:2.2")
    implementation("org.slf4j:slf4j-api:2.0.13")
    implementation("org.slf4j:slf4j-simple:2.0.13")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

docker {
    dependsOn(tasks.distTar.get())
    name = "${rootProject.name}:${dockerTag}"
    tag("RemoteRepos", "${repositoryUrl}:${dockerTag}")
    files(tasks.distTar.get().archiveFile)
    buildArgs(mapOf("ARTIFACT_NAME" to tasks.distTar.get().archiveFileName.get()))
}