/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.8/userguide/building_java_projects.html in the Gradle documentation.
 */
import org.sonarqube.gradle.SonarTask

version = "v0.0.1"

plugins {
    id("org.owasp.dependencycheck") version "12.2.2"
    jacoco
    id("org.sonarqube") version "7.3.0.8198"
    id("com.diffplug.spotless") version "8.4.0"

    checkstyle

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit)

    // This dependency is used by the application.
    implementation(libs.guava)
    implementation(platform(libs.beam.sdks.java.google.cloud.platform.bom))
    implementation("org.apache.beam:beam-sdks-java-core")
    implementation("org.apache.beam:beam-runners-direct-java")
    implementation("org.apache.beam:beam-sdks-java-io-rrio")
    implementation("org.apache.beam:beam-sdks-java-extensions-avro")
    implementation("org.apache.beam:beam-sdks-java-io-google-cloud-platform")
    implementation("com.google.api-client:google-api-client")
    implementation("org.hamcrest:hamcrest")

    compileOnly(libs.auto.value.annotations)
    annotationProcessor(libs.auto.value)

    // Logging
    implementation(libs.slf4j.api)
    implementation(libs.slf4j.simple)

    // Jackson
    implementation(platform(libs.jackson.bom))
    implementation("com.fasterxml.jackson.core:jackson-core")
    implementation("com.fasterxml.jackson.core:jackson-databind")
    implementation("com.fasterxml.jackson.core:jackson-annotations")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = "org.example.App"
}

checkstyle {
    toolVersion ="13.4.0"
    configFile = file("${projectDir}/../config/checkstyle/checkstyle.xml")
    configProperties = mapOf(
        "org.checkstyle.google.severity" to "error",
        "org.checkstyle.google.suppressionfilter.config" to
                "${projectDir}/../config/checkstyle/checkstyle-suppressions.xml"
    )
}


configure<org.owasp.dependencycheck.gradle.extension.DependencyCheckExtension> {
    nvd.apiKey = System.getenv("NVD_API_KEY")
    autoUpdate = true

    // Fail build if vulnerabilities are found
    failBuildOnCVSS = 0.0F
}

sonar {
    properties {
        property("sonar.host.url", System.getenv("SONAR_HOST_URL"))
        property("sonar.projectKey", System.getenv("SONAR_PROJECT_KEY"))
        property("sonar.organization",  System.getenv("SONAR_ORGANIZATION_NAME"))
        property("sonar.sources", "src/main/java")
        property("sonar.tests", "src/test/java")
        property("sonar.coverage.jacoco.xmlReportPaths",
            "build/reports/jacoco/test/jacocoTestReport.xml")
    }
}

spotless {
    java {
        googleJavaFormat()
        importOrder()
        removeUnusedImports()
        formatAnnotations()
        tarTree("**/*.java")
    }
}

tasks.named<Test>("test") {
    // Nothing to customize yet
}

tasks.named<JacocoReport>("jacocoTestReport") {
    reports {
        xml.required = true
        csv.required = false
        html.required = false
    }
}

tasks.named<SonarTask>("sonar") {
    dependsOn("jacocoTestReport")
}