/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class AppTest {
  /** */
  @Test
  public void appHasAGreeting() {
    assertTrue(true);
  }
}
