name: NVD db refresh

on:
  schedule:
    - cron: "0 21 * * *"

jobs:
  refresh:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v5
      - name: Setup java
        uses: actions/setup-java@v5
        with:
          distribution: corretto
          java-version: 21
      - name: Cache nvd
        uses: actions/cache@v4
        with:
          path: ~/.gradle/dependency-check-data
          key: "dependency-check-data"
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: gradle-${{ hashFiles('**/*.gradle.kts') }}
      - name: Purge database
        run: ./gradlew dependencyCheckPurge
      - name: Update database
        run: ./gradlew dependencyCheckUpdate