name: SAST

on:
  pull_request:

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          build-scan-publish: true
          build-scan-terms-of-use-url: "https://gradle.com/terms-of-service"
          build-scan-terms-of-use-agree: "yes"
      - name: Cache nvd
        uses: actions/cache@v4
        with:
          path: ~/.gradle/dependency-check-data
          key: ${{ github.repository }}
      - name: Run dependency check for JARS
        run: ./gradlew dependencyCheckAnalyze
      - name: Run code analysis
        run: echo "Not implemented"