name: "Vulnerability test"

on:
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Cache nvd
        uses: actions/cache@v4
        with:
          path: ~/.gradle/dependency-check-data
          key: "dependency-check-data"
      - name: Run dependency check for JARS
        run: ./gradlew dependencyCheckAnalyze
  sast:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: sonar-gradle-${{ hashFiles('**/*.gradle') }}
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: ./gradlew build sonar --info -Dsonar.qualitygate.wait=true