name: "Vulnerability test"

on:
  pull_request:

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Cache nvd
        uses: actions/cache@v4
        with:
          path: ~/.gradle/dependency-check-data
          key: "dependency-check-data"
      - name: Run dependency check for JARS
        run: ./gradlew dependencyCheckAnalyze
  sast:
    runs-on: ubuntu-latest
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
      - name: Run code analysis
        run: echo "Not implemented"